http://localhost:5000/users
Content-Type: application/json

{
  "users" : [
    {
      "id" : 1,
      "account" : "abc1234",
      "userName" : "뚜뚜루",
      "address" : "서울"
    },
    {
      "id" : 2,
      "account" : "aaaaa",
      "userName" : "다라랑",
      "address" : "강원도"
    }
  ],
  "boards" : []
}